title: Καλλίνικος
description: Ο Καλλίνικος είναι μια πλατφόρμα με αλγορίθμους η οποία δημιουργήθηκε με σκοπό την διευκόλυνση της εξάσκησης των ελληνόγλωσσων μαθητών για τους διαγωνισμούς πληροφορικής.
timezone: Europe/Athens
permalink: /:title
highlighter: rouge
gems:
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

collections_dir: contests

collections:
  25-PDP:
    output: true
    permalink: /:collection/:name
  26-PDP:
    output: true
    permalink: /:collection/:name
  27-PDP:
    output: true
    permalink: /:collection/:name
  29-PDP:
    output: true
    permalink: /:collection/:name
    
defaults:
  - scope:
      path: ""
      type: "25-PDP"
    values:
      contest: "25ος ΠΔΠ"
      contest_url: "25-PDP"
  - scope:
      path: ""
      type: "26-PDP"
    values:
      contest: "26ος ΠΔΠ"
      contest_url: "26-PDP"
  - scope:
      path: ""
      type: "27-PDP"
    values:
      contest: "27ος ΠΔΠ"
      contest_url: "27-PDP"
  - scope:
      path: ""
      type: "29-PDP"
    values:
      contest: "29ος ΠΔΠ"
      contest_url: "29-PDP"
